// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"
	models "fp_kata/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AuthorizationService is an autogenerated mock type for the AuthorizationService type
type AuthorizationService struct {
	mock.Mock
}

// IsAuthorized provides a mock function with given fields: ctx, userId, order
func (_m *AuthorizationService) IsAuthorized(ctx context.Context, userId int, order models.Order) (bool, error) {
	ret := _m.Called(ctx, userId, order)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Order) (bool, error)); ok {
		return rf(ctx, userId, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Order) bool); ok {
		r0 = rf(ctx, userId, order)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.Order) error); ok {
		r1 = rf(ctx, userId, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthorizationService creates a new instance of AuthorizationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationService {
	mock := &AuthorizationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
